// tools
Js.include("./jsmake-scripts/tools_gcc.js");
Js.include("./jsmake-scripts/tools_github.js");
Js.include("./jsmake-scripts/tools_cmake.js");
Js.include("./jsmake-scripts/tools_compile_shaders.js");

Js.include("./jsmake-scripts/logo.js");

Js.include("./jsmake-scripts/dep_agg.js");
Js.include("./jsmake-scripts/dep_bx.js");
Js.include("./jsmake-scripts/dep_bimg.js");
Js.include("./jsmake-scripts/dep_bgfx.js");
Js.include("./jsmake-scripts/dep_glfw.js");
Js.include("./jsmake-scripts/dep_sdl2.js");
Js.include("./jsmake-scripts/dep_glm.js");
Js.include("./jsmake-scripts/dep_nanovg.js");
Js.include("./jsmake-scripts/dep_vfspp.js");
Js.include("./jsmake-scripts/dep_nfd.js");
Js.include("./jsmake-scripts/dep_jsoncpp.js");
Js.include("./jsmake-scripts/dep_stb.js");
Js.include("./jsmake-scripts/dep_miniaudio.js");
Js.include("./jsmake-scripts/dep_rtaudio.js");
Js.include("./jsmake-scripts/dep_yoga.js");
Js.include("./jsmake-scripts/dep_cereal.js");
Js.include("./jsmake-scripts/dep_tinyobjloader.js");
Js.include("./jsmake-scripts/dep_gainput.js");
Js.include("./jsmake-scripts/dep_fmt.js");
Js.include("./jsmake-scripts/dep_miniz.js");
Js.include("./jsmake-scripts/dep_skia.js");
Js.include("./jsmake-scripts/dep_quickjs.js");
Js.include("./jsmake-scripts/dep_assimp.js");
Js.include("./jsmake-scripts/dep_libogg.js");
Js.include("./jsmake-scripts/dep_theora.js");
Js.include("./jsmake-scripts/dep_vorbis.js");
Js.include("./jsmake-scripts/dep_lohmann_json.js");
Js.include("./jsmake-scripts/dep_tinygltf.js");
Js.include("./jsmake-scripts/dep_minimp3.js");
Js.include("./jsmake-scripts/dep_vst3sdk.js");
Js.include("./jsmake-scripts/dep_raylib.js");
